DROP TABLE MVC_BOARD;
DROP SEQUENCE MVC_BOARD_SEQ;
CREATE SEQUENCE MVC_BOARD_SEQ MAXVALUE 999999 NOCACHE;
CREATE TABLE MVC_BOARD(
    bID         NUMBER(6),
    bNAME       VARCHAR2(50) NOT NULL,
    bTITLE      VARCHAR2(100) NOT NULL,
    bCONTENT    VARCHAR2(1000),
    bDATE       DATE DEFAULT SYSDATE NOT NULL,
    bHIT        NUMBER(6) DEFAULT 0 NOT NULL,
    bGROUP      NUMBER(6) NOT NULL,
    bSTEP       NUMBER(3) NOT NULL,
    bINDENT     NUMBER(3) NOT NULL,
    bIP         VARCHAR2(20) NOT NULL,
    PRIMARY KEY(bID)
);
SELECT * FROM MVC_BOARD;
--리스트
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MVC_BOARD ORDER BY bGROUP DESC, bSTEP) A) WHERE RN BETWEEN 1 AND 5;
--총갯수
SELECT COUNT(*) CNT FROM MVC_BOARD;
글쓰기
INSERT INTO MVC_BOARD (bID,bNAME,bTITLE,bCONTENT,bGROUP,bSTEP,bINDENT,bIP) 
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'HONG', 'TITLE','WOW',MVC_BOARD_SEQ.CURRVAL,0,0,'127.0.0.1');
INSERT INTO MVC_BOARD (bID,bNAME,bTITLE,bCONTENT,bGROUP,bSTEP,bINDENT,bIP) 
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'KIM', 'TITLEKIM','KIMKKIM',MVC_BOARD_SEQ.CURRVAL,0,0,'127.0.0.2');

--dto가져오기
SELECT * FROM MVC_BOARD WHERE BID=2;
--조회수
UPDATE MVC_BOARD SET bHIT = bHIT+1 WHERE bID=1;
--답변글 STEPA
UPDATE MVC_BOARD SET bSTEP = bSTEP+1 WHERE bSTEP>0 AND bGROUP=2;

--답변쓰기
INSERT INTO MVC_BOARD (bID,bNAME,bTITLE,bCONTENT,bGROUP,bSTEP,bINDENT,bIP) 
    VALUES (MVC_BOARD_SEQ.NEXTVAL, 'BONG', 'RE:KIM','NONO',113,1,1,'127.0.0.1');
--수정하기
UPDATE MVC_BOARD SET bNAME='HUL',bTITLE='TITLECANGE',bCONTENT='WOWWOW',bIP='0' WHERE bID=2; 
    
--삭제하기
DELETE FROM MVC_BOARD WHERE BID=1;

COMMIT;
SELECT BID, BNAME, BTITLE, BCONTENT, TO_CHAR(BDATE, 'YY/MM/DD HH:MI:SS') FROM MVC_BOARD;